#!/usr/bin/env python3
"""
Symbolic Einstein tensor export for the equatorial frame-dragging metric slice.

Exports:
  docs/derived_equations_summary.tex  — compact main-body summary
  docs/appendix_tensor_components.tex — full G_{mu nu} components (Appendix A)

Signature: (-,+,+,+). Geometric units c = G = 1.
"""

from __future__ import annotations

import sys
from pathlib import Path

import sympy as sp

sys.path.insert(0, str(Path(__file__).resolve().parent))
from tensor_core import (  # noqa: E402
    G_LABELS,
    compute_curvature_pipeline,
    explicit_metric_profiles,
    latex_component_align,
    latex_multiline_aligned,
    nonzero_components,
    substitute_explicit_profiles,
)

ROOT = Path(__file__).resolve().parents[1]
OUT_SUMMARY = ROOT / "docs" / "derived_equations_summary.tex"
OUT_APPENDIX = ROOT / "docs" / "appendix_tensor_components.tex"


def export_summary(R_scalar: sp.Expr, n_comps: int) -> str:
    """Compact main-body summary (no overflowing component expansions)."""
    prof = explicit_metric_profiles()
    b = prof["b"]
    R_exp = substitute_explicit_profiles(R_scalar)
    # Use the comparatively compact G_rr radial component as a representative invariant
    return (
        r"% Auto-generated by scripts/derive_tensors.py — main-body summary"
        "\nSubstituting the explicit profiles~\\eqref{eq:profiles} on the equatorial "
        f"slice ($\\theta=\\pi/2$), {n_comps} components of $\\Gmn$ are non-zero: "
        r"$G_{tt}$, $G_{t\varphi}$, $G_{rr}$, $G_{\theta\theta}$, and $G_{\varphi\varphi}$."
        "\nThe effective stress-energy is $\\Tmn=\\Gmn/(8\\pi)$ component-wise.\n"
        "Key scalar invariants are\n"
        "\\begin{align}\n"
        f"\\det(g_{{\\mu\\nu}}) &= -\\frac{{r^{{5}} e^{{2\\Phi(r)}}}}{{r - b(r)}}, "
        f"\\quad b(r)={sp.latex(b)}, \\nonumber\\\\\n"
        r"R &= \mathcal{R}(\gamma,\alpha,\omega_0,\beta;r,r_0)"
        r"\quad\text{(explicit form in Appendix~\ref{app:tensors})}."
        "\n\\end{align}\n"
        "The radial component $G_{rr}$ admits a compact closed form; "
        "all component expansions appear in Appendix~\\ref{app:tensors}.\n"
    )


def export_appendix(g_comps: list, R_scalar: sp.Expr) -> str:
    """Full tensor components for Appendix A."""
    lines = [
        "% Auto-generated by scripts/derive_tensors.py — Appendix A\n",
        "% Equatorial slice theta = pi/2; signature (-+++); c = G = 1\n",
        "\\begin{footnotesize}\n",
        latex_component_align(g_comps, G_LABELS),
        latex_multiline_aligned("R", R_scalar),
        "\\end{footnotesize}\n",
    ]
    return "".join(lines)


def export_latex(data: dict) -> None:
    G = data["G"]
    R_scalar = data["R_scalar"]
    g_comps = nonzero_components(G)

    OUT_SUMMARY.parent.mkdir(parents=True, exist_ok=True)
    OUT_SUMMARY.write_text(export_summary(R_scalar, len(g_comps)), encoding="utf-8")
    OUT_APPENDIX.write_text(export_appendix(g_comps, R_scalar), encoding="utf-8")
    print(f"Wrote {OUT_SUMMARY}")
    print(f"Wrote {OUT_APPENDIX} ({len(g_comps)} non-zero G components)")


def main() -> int:
    print("Computing equatorial Einstein tensor with explicit profiles ...")
    data = compute_curvature_pipeline(equatorial=True, explicit_profiles=True)
    export_latex(data)
    print("Done.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
