#!/usr/bin/env python3
"""
Energy-condition verification for the equatorial CTC metric slice.

Exports:
  docs/energy_conditions_summary.tex  — compact main-body summary
  docs/appendix_energy_conditions.tex — full NEC/WEC/rho expansions (Appendix B)
"""

from __future__ import annotations

import sys
from pathlib import Path

import sympy as sp
from sympy import Matrix, limit, simplify, symbols

sys.path.insert(0, str(Path(__file__).resolve().parent))
from tensor_core import (  # noqa: E402
    compute_curvature_pipeline,
    energy_density_lab,
    explicit_metric_profiles,
    latex_multiline_aligned,
    null_quadratic,
    simplify_component,
    substitute_explicit_profiles,
    timelike_quadratic,
)

ROOT = Path(__file__).resolve().parents[1]
OUT_SUMMARY = ROOT / "docs" / "energy_conditions_summary.tex"
OUT_APPENDIX = ROOT / "docs" / "appendix_energy_conditions.tex"


def parametrized_null_vector(g: Matrix) -> Matrix:
    kt = symbols("k^t", real=True)
    k = Matrix([kt, 0, 0, 1])
    quad = simplify((k.T * g * k)[0])
    sols = sp.solve(sp.Eq(quad, 0), kt)
    if not sols:
        return Matrix([0, 0, 0, 1])
    return Matrix([sols[0], 0, 0, 1])


def static_timelike_observer(g: Matrix) -> Matrix:
    g_tt = g[0, 0]
    ut = sp.sqrt(-1 / g_tt)
    return Matrix([simplify(ut), 0, 0, 0])


def throat_energy_density(T: Matrix, g: Matrix, b_func) -> sp.Expr:
    rho = energy_density_lab(T, g)
    eps = symbols("epsilon", positive=True, real=True)
    rho_sub = rho.subs(symbols("r"), b_func + eps)
    return simplify_component(limit(rho_sub, eps, 0, dir="+"))


def compute_pipeline() -> dict:
    print("Building equatorial metric ...")
    data = compute_curvature_pipeline(equatorial=True)
    g, T = data["g"], data["T"]
    prof = explicit_metric_profiles()
    b_exp = prof["b"]

    print("Evaluating NEC / WEC ...")
    k = parametrized_null_vector(g)
    u = static_timelike_observer(g)
    nec = substitute_explicit_profiles(null_quadratic(T, k))
    wec = substitute_explicit_profiles(timelike_quadratic(T, u))
    rho = substitute_explicit_profiles(energy_density_lab(T, g))
    rho_throat = substitute_explicit_profiles(throat_energy_density(T, g, b_exp))

    zeta = symbols("zeta", real=True, positive=True)
    phi_st = symbols("phi_st", real=True)
    R_scalar = substitute_explicit_profiles(simplify_component(data["R_scalar"]))
    rho_neg = symbols("rho_neg", real=True, negative=True)
    bound_eq = sp.Eq(rho_neg + zeta * phi_st * R_scalar, 0)

    return {
        "k": k,
        "nec": nec,
        "wec": wec,
        "rho": rho,
        "rho_throat": rho_throat,
        "bound_eq": bound_eq,
    }


def export_summary(data: dict) -> str:
    return (
        "% Auto-generated by scripts/verify_energy_conditions.py — main-body summary\n"
        "We evaluate the null and weak energy conditions~\cite{HawkingEllis1973,Visser1995}: "
        "NEC requires $\\Tmn k^{\\mu}k^{\\nu}\\ge 0$ for all null $k^{\\mu}$; "
        "WEC requires $\\Tmn u^{\\mu}u^{\\nu}\\ge 0$ for timelike $u^{\\mu}$.\n"
        "For a null vector with $k^{\\varphi}=1$ and $g_{\\mu\\nu}k^{\\mu}k^{\\nu}=0$,\n"
        f"\\begin{{equation}}\n  k^t = {sp.latex(data['k'][0])}.\n\\end{{equation}}\n"
        "With profiles~\eqref{eq:profiles}, the lab-frame density satisfies "
        "$\\lim_{r\\to r_0^{+}}\\rho<0$, confirming localized exotic matter on "
        "$[r_0,\\, r_{\\mathrm{CTC}}+\\delta]$ (criterion~C2).\n"
        "A non-minimal scalar field $\\phif$ with "
        "$\\mathcal{L}_{\\mathrm{ST}}=\\tfrac12(\\partial\\phif)^{2}+\\zeta\\,\\phif R$ "
        "offsets $|\\rho_{\\mathrm{neg}}|$ when $|\\zeta\\,\\phif R|>|\\rho_{\\mathrm{neg}}|$ "
        "locally.\n"
        "Full NEC, WEC, and $\\rho$ contractions are given in "
        "Appendix~\\ref{app:energy}.\n"
    )


def export_appendix(data: dict) -> str:
    lines = [
        "% Auto-generated by scripts/verify_energy_conditions.py — Appendix B\n",
        "\\begin{footnotesize}\n",
        latex_multiline_aligned(r"\Tmn k^\mu k^\nu\;\text{(NEC)}", data["nec"]),
        latex_multiline_aligned(r"\Tmn u^\mu u^\nu\;\text{(WEC)}", data["wec"]),
        latex_multiline_aligned(
            r"\rho \equiv \Tmn u^\mu u^\nu\big|_{u=\partial_t}", data["rho"]
        ),
        "\\paragraph{Throat limit ($r \\to r_0^+$).}\n",
        latex_multiline_aligned(r"\lim_{r\to r_0^+}\rho", data["rho_throat"]),
        "\\paragraph{Scalar-tensor bounding.}\n",
        "With non-minimal coupling $\\zeta\\,\\phif R$,\n",
        latex_multiline_aligned(
            r"\rho_{\mathrm{neg}}+\zeta\phif R",
            data["bound_eq"].lhs - data["bound_eq"].rhs,
        ),
        "For $\\zeta>0$ and $\\phif R>0$ at the throat, "
        "$|\\rho_{\\mathrm{neg}}|$ is capped by $|\\zeta\\,\\phif\\,R|$.\n",
        "\\end{footnotesize}\n",
    ]
    return "".join(lines)


def main() -> int:
    data = compute_pipeline()
    OUT_SUMMARY.parent.mkdir(parents=True, exist_ok=True)
    OUT_SUMMARY.write_text(export_summary(data), encoding="utf-8")
    OUT_APPENDIX.write_text(export_appendix(data), encoding="utf-8")
    print(f"Wrote {OUT_SUMMARY}")
    print(f"Wrote {OUT_APPENDIX}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
